name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 161.22.44.87
          port: 2222
          username: acoray
          keys: ${{ secrets.PRIVATE_KEY }}
          script: "cd /var/www/html/SimpleApp_A4; git pull github master;npm run build"
